data:
  path: "./cleaned"
  seq_len: 32
  batch_size: 32
  is_generation: False


model:
  lr: 0.001
  note_emb_size: 100
  dur_emb_size: 100
  num_recurrent_layers: 2
  hidden_size: 256
  use_lstm: False # RGU by default
  sampling_temperature: 0